import Head from 'next/head'
import React from 'react'
import styles from './Layout.module.css'
import { Roboto } from 'next/font/google'
import AppHeader from '../AppHeader'

const roboto = Roboto({ subsets: ['latin'], weight: '400' })

interface Props {
  children: React.ReactNode
}

const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${roboto.className} ${styles.app}` }>
        <AppHeader />
        <main className={styles.main}>
          {children}
        </main>
        <footer>footer</footer>
      </div>
    </>
  )
}

export default Layout
